replicaCount: 2

image:
  repository: 962765734677.dkr.ecr.us-east-1.amazonaws.com/eks-gitops/api-service
  pullPolicy: IfNotPresent
  tag: "722f20920cced170f2521ba5ad8021f788efe88e"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

serviceAccount:
  create: true
  name: "api-service-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::962765734677:role/eks-gitops-platform-api-service"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

env:
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/962765734677/order-processing-queue"
  DYNAMODB_TABLE: "order-storage-table"

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: '8000'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: api-service

affinity: {} 