apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lumbenlengo/eks-gitops-platform.git
    targetRevision: HEAD
    path: terraform/modules/addons/charts/worker-service
    helm:
      values: |
        image:
          repository: "962765734677.dkr.ecr.us-east-1.amazonaws.com/eks-gitops/worker-service"
          tag: "latest"
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::962765734677:role/eks-gitops-platform-worker-service"
        env:
          SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/962765734677/eks-gitops-worker-queue"
  destination:
    server: https://kubernetes.default.svc
    namespace: worker-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
