name: Terraform Job Template
on:
  workflow_call:
    inputs:
      layer: { type: string, required: true }
      tf_key: { type: string, required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "1.7.5", terraform_wrapper: false }

      - name: Terraform Init
        working-directory: terraform/layers/${{ inputs.layer }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=eks-gitops-platform-tfstate-962765734677" \
            -backend-config="key=${{ inputs.tf_key }}" \
            -backend-config="region=us-east-1"

      - name: Terraform Validate
        working-directory: terraform/layers/${{ inputs.layer }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/layers/${{ inputs.layer }}
        run: |
          terraform plan -lock-timeout=10m -input=false -out=tfplan -var-file="${{ github.workspace }}/terraform/environments/prod/terraform.tfvars"
          terraform show -json tfplan > plan.json
          if jq -e '.resource_changes[]? | select(.change.actions[] == "delete")' plan.json; then
            echo "::error::Destroy operations detected in plan!"
            exit 1
          fi

      - name: Terraform Apply
        working-directory: terraform/layers/${{ inputs.layer }}
        run: terraform apply -lock-timeout=10m -input=false -auto-approve tfplan